plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'lib', include: ['*.jar'])
}

application {
    mainClass = 'com.dam.finanzas.main.Inicio'
}

tasks.named('run') {
    standardInput = System.in
}
